openapi: 3.0.2
info:
  title: MIC Customer service
  description: Mic by management customer
  contact:
    name: Roberto Benitez
    email: rbenitez_20_95@hotmail.com
  license:
    name: rbenitez
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Desarrollo
paths:
  /clientes:
    post:
      tags:
        - save
      summary: crear clientes.
      description: |
        ## 👋 Propósito
        
        Mic de Negocio permite crear clientes.

      operationId: save
      parameters:
        - $ref: "#/components/parameters/x-user-id"
        - $ref: "#/components/parameters/x-consumer-id"
        - $ref: "#/components/parameters/x-transaction-id"
        - $ref: "#/components/parameters/x-caller-id"

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestBodyCrearUsuario'
        required: true
      responses:
        "200":
          $ref: '#/components/responses/OkCreated'
        "202":
          $ref: '#/components/responses/Accepted'
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "405":
          $ref: '#/components/responses/NotAllowed'
        "500":
          $ref: '#/components/responses/InternalServerErrorStatus'
        "504":
          $ref: '#/components/responses/GatewayTimeoutErrorStatus'
  /clientes/{id}:
    get:
      tags:
        - obtenercliente
      summary: obtener cliente en base a su id
      description: |
        ## 👋 Propósito
        
        Esta Mic de Negocio permite obtener Clientes.

      operationId: obtenercliente
      parameters:
        - $ref: "#/components/parameters/id"
        - $ref: "#/components/parameters/x-user-id"
        - $ref: "#/components/parameters/x-consumer-id"
        - $ref: "#/components/parameters/x-transaction-id"
        - $ref: "#/components/parameters/x-caller-id"

      responses:
        "200":
          $ref: '#/components/responses/OkCreated'
        "202":
          $ref: '#/components/responses/Accepted'
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "405":
          $ref: '#/components/responses/NotAllowed'
        "500":
          $ref: '#/components/responses/InternalServerErrorStatus'
        "504":
          $ref: '#/components/responses/GatewayTimeoutErrorStatus'
    put:
      tags:
        - update
      summary: actualizar cliente en base a su id
      description: |
        ## 👋 Propósito
        
        Esta Mic de Negocio permite actualizar clientes.

      operationId: update
      parameters:
        - $ref: "#/components/parameters/id"
        - $ref: "#/components/parameters/x-user-id"
        - $ref: "#/components/parameters/x-consumer-id"
        - $ref: "#/components/parameters/x-transaction-id"
        - $ref: "#/components/parameters/x-caller-id"

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/requestBodyCrearUsuario'
        required: true
      responses:
        "200":
          $ref: '#/components/responses/OkCreated'
        "202":
          $ref: '#/components/responses/Accepted'
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "405":
          $ref: '#/components/responses/NotAllowed'
        "500":
          $ref: '#/components/responses/InternalServerErrorStatus'
        "504":
          $ref: '#/components/responses/GatewayTimeoutErrorStatus'
    delete:
      tags:
        - delete
      summary: eliminar cliente en base a su id
      description: |
        ## 👋 Propósito
        
        Esta Mic de Negocio permite eliminar clientes.

      operationId: delete
      parameters:
        - $ref: "#/components/parameters/id"
        - $ref: "#/components/parameters/x-user-id"
        - $ref: "#/components/parameters/x-consumer-id"
        - $ref: "#/components/parameters/x-transaction-id"
        - $ref: "#/components/parameters/x-caller-id"

      responses:
        "200":
          $ref: '#/components/responses/OkDelete'
        "202":
          $ref: '#/components/responses/Accepted'
        "400":
          $ref: '#/components/responses/BadRequest'
        "401":
          $ref: '#/components/responses/Unauthorized'
        "404":
          $ref: '#/components/responses/NotFound'
        "405":
          $ref: '#/components/responses/NotAllowed'
        "500":
          $ref: '#/components/responses/InternalServerErrorStatus'
        "504":
          $ref: '#/components/responses/GatewayTimeoutErrorStatus'
components:
  schemas:
    requestBodyCrearUsuario:
      description: Datos para crear un cliente.
      type: object
      properties:
        customerType:
          type: string
          maxLength: 20
        dni:
          type: string
          maxLength: 8
          minLength: 8
        names:
          type: string
          maxLength: 50
        lastName:
          type: string
          maxLength: 50
        address:
          type: string
          maxLength: 254
        phone:
          type: string
          maxLength: 9
          minLength: 9
        email:
          type: string
          maxLength: 50
      required:
        - customerType
        - dni
        - names
        - lastName
        - address
        - phone
        - email
      example:
        customerType: "NORMAL"
        dni: "12345678"
        names: "Roberto"
        lastName: "Benitez Cruzado"
        address: "Av. los sauces 371"
        phone: "915184044"
        email: "rbenitez_20_95@hotmail.com"
    StatusResponseOKDelete:
      type: object
      properties:
        message:
          type: string
    StatusResponseData:
      type: object
      properties:
        id:
          type: string
          maxLength: 50
        customerType:
          type: string
          maxLength: 20
        dni:
          type: string
          maxLength: 8
          minLength: 8
        names:
          type: string
          maxLength: 50
        lastName:
          type: string
          maxLength: 50
        address:
          type: string
          maxLength: 250
        phone:
          type: string
        email:
          type: string
          maxLength: 50
        dateCreated:
          type: string
        dateUpdate:
          type: string
    StatusResponse:
      type: object
      properties:
        status:
          type: integer
        statusCode:
          type: integer
        type:
          type: string
        title:
          type: string
        detail:
          type: string
        instanse:
          type: string
      description: Modelo de respuesta de error.
    StatusResponse_error:
      type: object
      properties:
        errorMessage:
          type: string
        errorCode:
          type: string
        errorDetails:
          type: array
          items:
            type: object
  parameters:
    x-consumer-id:
      name: x-consumer-id
      in: header
      description: 'Datos del aplicativo o canal de origen. Formato: {canal}.'
      required: true
      style: simple
      explode: false
      schema:
        type: string
      example: landingpasivos
    x-transaction-id:
      name: x-transaction-id
      in: header
      description: 'Identificador con estructura definida generado en el canal que identifica a un paso de un flujo funcional y que se propaga en todos los componentes.'
      required: true
      style: simple
      explode: false
      schema:
        type: string
      example: ladingpasivos.aperturacuentadigital.Fri Oct 20 10-20-35 GMT-05-00 2023.30f14c6c1fc85cba12bfd093aa93aa
    x-caller-id:
      name: x-caller-id
      in: header
      description: 'Url del servicio que originó la petición'
      required: true
      style: simple
      explode: false
      schema:
        type: string
      example: https://bs-aperturarcuenta-prod.apps.ocpnoprod.domibco.com.pe/loans_deposits/savingsAccount/v1/ahorros/aperturar
    x-user-id:
      name: x-user-id
      in: header
      description:
        'Identificador del usuario.'
      required: true
      style: simple
      explode: false
      schema:
        type: string
      example: "9876599"
    id:
      name: id
      in: path
      description: User ID
      style: simple
      required: true
      schema:
        type: string
      example: "7287ge99h29ege28239e"
  responses:
    OkCreated:
      description: Respuesta exitosa.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusResponseData'
          examples:
            OK:
              $ref: '#/components/examples/OK'
    OkDelete:
      description: Respuesta exitosa.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusResponseOKDelete'
          examples:
            OK:
              $ref: '#/components/examples/OKDelete'
    Accepted:
      description: Respuesta con error de validación y/o reglas de negocio.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusResponse'
          examples:
            Accepted:
              $ref: '#/components/examples/Accepted'
    BadRequest:
      description: 'Respuesta que indica que no se ha enviado un campo obligatorio en el body o header o no se ha cumplido con la estructura del contrato.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusResponse'
          examples:
            BadRequest:
              $ref: '#/components/examples/BadRequest'
    NotFound:
      description: Respuesta que indica que no se encontró el recurso solicitado.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusResponse'
          examples:
            NotFound:
              $ref: '#/components/examples/NotFound'
    Unauthorized:
      description: Respuesta que indica Auth Token not found or not authorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusResponse'
          examples:
            NotFound:
              $ref: '#/components/examples/Unauthorized'
    NotAllowed:
      description: Respuesta que indica metodo no permitido
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusResponse'
          examples:
            NotAllowed:
              $ref: '#/components/examples/NotAllowed'
    InternalServerErrorStatus:
      description: Respuesta con error interno del servidor.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusResponse'
          examples:
            InternalServerError:
              $ref: '#/components/examples/InternalServerErrorStatus'
    GatewayTimeoutErrorStatus:
      description: Respuesta con error de timeout del servidor.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/StatusResponse'
          examples:
            GatewayTimeout:
              $ref: '#/components/examples/GatewayTimeoutErrorStatus'
  examples:
    OK:
      value:
        id: "6f218e9eeebo12p"
        customerType: "NORMAL"
        dni: "74084225"
        names: "Roberto"
        lastName: "Benitez Cruzado"
        address: "Av. Los sauces 371"
        phone: "915184044"
        email: "rbenitez_20_95@hotmail.com"
        dateCreated: "2017-07-21T17:32:28Z"
        dateUpdate: "2017-07-21T17:32:28Z"
    Accepted:
      value:
        statusCode: 202
        type: '{http://loansdeposits-dev.apps.ocpnoprod.domibco.com.pe/mic-bs-loans-deposits-savings-account-aperturarcuenta/v1/ahorros/aperturar}'
        title: Número de producto no válido.
        detail: mensaje:Aperturar cuenta
        instance: "{/mic-bs-loans-deposits-savings-account-aperturarcuenta/v1/ahorros/aperturar}"
    OKDelete:
      value:
        message: "Cuenta bancaria eliminada exitosamente"
    BadRequest:
      value:
        statusCode: 400
        type : "data:OperationNotFound"
        title : "Resource Not Found"
        detail : "Unable to match incoming request to an operation."
        instanse : "https://loansdeposits-dev.apps.ocpnoprod.domibco.com.pe/mic-bs-loans-deposits-savings-account-aperturarcuenta/v1/ahorros/aperturar"
    Unauthorized:
      value:
        statusCode: 401
        type: "data:SubscriptionKeyNotFound"
        title: "Access Denied"
        detail: "Access denied due to missing subscription key. Make sure to include subscription key when making requests to an API."
        instance: "https://loansdeposits-dev.apps.ocpnoprod.domibco.com.pe/mic-bs-loans-deposits-savings-account-aperturarcuenta/v1/ahorros/aperturar"
    NotFound:
      value:
        statusCode: 404
        type : "data:OperationNotFound"
        title : "Resource not found"
        detail : "Unable to match incoming request to an operation."
        instanse : "https://loansdeposits-dev.apps.ocpnoprod.domibco.com.pe/mic-bs-loans-deposits-savings-account-aperturarcuenta/v1/ahorros/aperturar"
    InternalServerErrorStatus:
      value:
        statusCode: 500
        type : "data:BackendConnectionFailure"
        title : "Internal Server Error"
        detail : "Name does not resolve"
        instanse : "https://loansdeposits-dev.apps.ocpnoprod.domibco.com.pe/mic-bs-loans-deposits-savings-account-aperturarcuenta/v1/ahorros/aperturar"
    GatewayTimeoutErrorStatus:
      value:
        statusCode: 504
        type : "data:BackendConnectionFailure"
        title : "Time out de conexion"
        detail : "Time out de conexion"
        instanse : "https://loansdeposits-dev.apps.ocpnoprod.domibco.com.pe/mic-bs-loans-deposits-savings-account-aperturarcuenta/v1/ahorros/aperturar"
    NotAllowed:
      value:
        statusCode: 405
        type : "data:BackendConnectionFailure"
        title : "Metodo no permitido"
        detail : "Metodo no permitido"
        instanse : "https://loansdeposits-dev.apps.ocpnoprod.domibco.com.pe/mic-bs-loans-deposits-savings-account-aperturarcuenta/v1/ahorros/aperturar"